version: '2.4'

services:
  mockserver:
    image: node:14
    working_dir: /app
    command: node mockserver.js
    cpus: 1
    cpuset: '0,1,2,3'
    scale: 4
    environment:
      PORT: 3500
      WEBHOOK_HOST: benchmark
      WEBHOOK_PORT: 4000
    networks:
      - http
    volumes:
      - .:/app

  benchmark:
    image: node:14
    working_dir: /app
    command: node distributed.js
    cpus: 1
    cpuset: '4,5,6,7'
    scale: 4
    restart: 'unless-stopped'
    depends_on:
      - mockserver
    environment:
      TARGET_HOST: mockserver
      TARGET_PORT: 3500
      WEBHOOK_PORT: 4000
      DATA_DIR: /data
      BATCH_REQUESTS: 400
      BATCH_TIMEFRAME: 500
    networks:
      - http
    volumes:
      - .:/app
      - ./data:/data

networks:
  http:
